--Script de creacion de tablas

CREATE TABLE USUARIOS (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDOS VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,

    INDBAJA INT DEFAULT 0,
    CREACIONTIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFICACIONTIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    BLOQUEOFINTIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDFALLOS INT DEFAULT 0
);

CREATE TABLE VIDEOS (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    TITULO VARCHAR(255) NOT NULL,
    AUTOR VARCHAR(100) NOT NULL,
    FECHACREACION DATE NOT NULL,
    DURACION TIME NOT NULL,
    NUMREPRODUCCIONES INT DEFAULT 0,
    DESCRIPCION VARCHAR(500),
    FORMATO VARCHAR(10) NOT NULL,
    LOCALIZACION VARCHAR(500) NOT NULL,

    CREACIONTIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFICACIONTIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USERID INT NOT NULL,
    CONSTRAINT FK_VIDEOS_USERS FOREIGN KEY (USERID) REFERENCES USUARIOS(ID)
);
